### ISSUE TITLE
下载android6.0源码并编译产生自己的镜像

### ISSUE THREAD

**Issue by pkulxy** [openthos/multidisp-analysis#6]
ubuntu下搭建交叉编译环境，编译android6.0源码

**Comment by pkulxy** [comment]
android源码较大，搭建环境已经完成，编译需要一定的时间。还需要搜一搜比较好的查看源码的工具。

**Comment by chyyuu** [comment]
现在有新的进展吗?

**Comment by pkulxy** [comment]
这个早就编译完成安到真机上了，过程放在这了
https://github.com/openthos/display-analysis/tree/master/repo/%E7%BC%96%E8%AF%91android%E6%BA%90%E7%A0%81
